### PR TITLE
Add paren mode

### LINKED ISSUE #3: preformatting corrupts file
I tried the parinfer plugin in lighttable and noticed the following two problems when the file is formatted on first edit.

```
(defn test
  ([a1]
  (println "test")
    )
  ([a1 a2]
    (println "test")))
```

becomes

```
(defn test
  ([a1])
  (println "test")

  ([a1 a2
    (println "test")]))
```

and

```
(defn read
  ([a1]
    (first (read a1 1)))
  ([a1 a2]
    (when (> a2 0)
      (try        
        (catch Exception e
          (throw e))))))
```

becomes

```
(defn read
  ([a1
    (first (read a1 1))])
  ([a1 a2
    (when (> a2 0)
      (try        
        (catch Exception e
          (throw e))))]))
```

### PR DESCRIPTION
**Pull request by mauricioszabo**
Fixes #3

### CODE REVIEW

**Comment by shaunlebron** [comment]
:clap: awesome!

**Comment by shaunlebron** [comment]
A couple things:
- `cursorDx` can only work consistently if Paren Mode runs synchronously to the edits being made.  The [300ms debounce for `on-change`](https://github.com/LightTable/LightTable/blob/a8a4f2e05c0f2295b6e093e87bcb06ab6f2e0303/src/lt/objs/editor.cljs#L663) will make this difficult.  For example, delete some chars on one line and then do the same on another without waiting longer than 300ms between edits.
  - maybe we can propose a new `:on-change-sync` behavior
  - in the meantime, we may be able to just hook the change event directly [like this](https://github.com/LightTable/LightTable/blob/a8a4f2e05c0f2295b6e093e87bcb06ab6f2e0303/src/lt/objs/editor.cljs#L121) after getting the editor's [object](https://github.com/LightTable/LightTable/blob/a8a4f2e05c0f2295b6e093e87bcb06ab6f2e0303/src/lt/objs/editor.cljs#L462) and its [CodeMirror instance](https://github.com/LightTable/LightTable/blob/a8a4f2e05c0f2295b6e093e87bcb06ab6f2e0303/src/lt/objs/editor.cljs#L20)
- if we get it to run synchronously, then the correct `cursorDx` is computed from the CodeMirror's `change` object passed to `on-change`, which has all the information we need about the type of edit.  I calculate it [here](https://github.com/shaunlebron/parinfer/blob/3144315283441a003413115fb87cd8c4a17a1613/site/src/parinfer_site/editor_support.cljs#L32-L38)

sorry, I'm short on time to help more this weekend.  plugin's looking good!

**Comment by mauricioszabo** [comment]
There's still some work to do, but I'll merge this and publish next tag to close #3.

**Comment by shaunlebron** [comment]
Paren Mode is behaving strangely.  For example:

``` clj
      (do
        (editor/set-val cm txt)
        (editor/scroll-to cm (.-left scroll) (.-top scroll))
        (.setCursor cm cursor)
        (.setHistory cm history))
```
1. Inserting a space before `(do` should indent all the following lines
2. Deleting a space before `(editor` on the second line shouldn't realign the rest of the lines.

You can see expected behavior with the online canonical editor:
http://shaunlebron.github.io/parinfer/demo

**Question**: I'd like to look at the `cursor-dx` value after it's computed but I'm not sure how to log that somewhere in Light Table.  `println` and `js/console.log` don't seem to show.  Thoughts?

**Comment by mauricioszabo** [comment]
@shaunlebron I know, I saw that behavior too. I'm opening a bug with your examples (https://github.com/mauricioszabo/lt_parinfer/issues/5)

I think, when we open the plugin on LightTable and ask to connect to the LightTable UI, we can use println to debug these things. The problem is when we change something in the code and LightTable doesn't update the behavior, but most of the time, it works.

I'm still investigating these issues, I just merged this PR because of #3, even knowing that paren-mode is not yet functioning as it had to.

**Comment by rundis** [comment]
Hi, hope it's ok to chip in

What behaviors is it that doesn't get updated ? 
Cljs code or code in the node_module ? 
I have never experienced problems with modifying the cljs code (as long as you remember to eval of course), so I'm curious what the problem might be and if it's possible to reproduce. If so I can have a look at it.

**Comment by mauricioszabo** [comment]
Hello, well, sometimes when I evaluate behaviors (or cljs code), things don't get updated. I'll try to make a code to be able to reproduce, because I'm not able, right now, to say in what situations this occurs. Sometimes, the plugin code simply doesn't get updated, and I need to run "reload behaviors" multiple times, or evaluate behaviors multiple times to force LightTable to update.

I'll try to reproduce this error and send it here. Thanks!

**Comment by mauricioszabo** [comment]
@shaunlebron created PR https://github.com/mauricioszabo/lt_parinfer/pull/6 with some considerations of what might be the problem. For now, paren-mode is working with two issues. I'll try to address then.

**Pull request merged**
